### ISSUE TITLE
Allow empty fivestar vote

### ISSUE THREAD

**Issue by plazmus** [backdrop-contrib/fivestar#13]
I have multiple fivestar fields on comments "Stars (rated while editing)" and I want to allow users to skip fivestar vote for some of them. It works fine in Drupal 7, but on Backdrop I get:
```SQLSTATE[22007]: Invalid datetime format: 1366 Incorrect integer value: '' for column 'field_rate_rating' at row 1```

**Comment by laryn** [comment]
I'll take a look, @plazmus. Thanks for the report!

**Comment by laryn** [comment]
I've done some testing, and: 

 - [fivestar_field_is_empty](https://github.com/backdrop-contrib/fivestar/blob/1.x-2.x/includes/fivestar.field.inc#L217-L226) seems to be returning TRUE, which is correct for an empty vote. I'm not sure why it's trying to save a value for an empty field...
 - Empty votes seem to work when attached to the node directly, or to a taxonomy term, or a user, and set to "rated while editing" so this **may** be particular to comments?  

@plazmus - This isn't a solution but just making sure I have my test comment vote set up the same as you -- do you have the "Voting target" set?
![Screen Shot 2019-11-12 at 2 02 58 PM](https://user-images.githubusercontent.com/871421/68706349-466b0800-0555-11ea-8015-7634dc355ef6.jpg)

I'm going to need to come back to it later -- anyone with ideas in the meantime please post!

**Comment by plazmus** [comment]
@laryn thanks for looking into it, yes I do have a Voting target, but tried with None as well - same result.

**Comment by plazmus** [comment]
I did some testing, somehow after changing voting target to None and widget type to (rated while viewing) then turning on and off "Allow users to cancel their ratings" I was able to save comments with empty rating.
Then I changed widget to (rated while editing) and it still worked.
As soon as I've changed voting target to Parent Node it shows the same error.

**Comment by laryn** [comment]
Interesting and strange. I wonder if the Parent Node issue could be related to https://api.backdropcms.org/change-records/node-entity-now-classed-object

**Comment by plazmus** [comment]
Ok, so if I return FALSE in fivestar_field_is_empty it works fine, well empty vote is saved as 0 and in Drupal it wasn't saving it at all, but at least it works.

**Comment by laryn** [comment]
I'm starting to wonder if this may be a core issue... see also:

 - https://github.com/backdrop-contrib/reference/issues/48
 - https://github.com/backdrop/backdrop-issues/issues/3873#issuecomment-503912153

**Comment by laryn** [comment]
@plazmus Are you able to test this core PR and see how it affects this issue? I did a quick preliminary and it looks like it might do it.

https://github.com/backdrop/backdrop/pull/3007/files

**Comment by plazmus** [comment]
Thanks @laryn, yes after applying changes from core PR empty fields are working as expected now.

**Comment by laryn** [comment]
Closing as this appears to be a core issue.
