### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by djzwerg** [backdrop-contrib/fivestar#14]
Because there were a few issues fixed would it be possible to provide a new release? Thanks in advance :-)

**Comment by laryn** [comment]
@djzwerg Are you able to test the latest dev version? I merged a few new commits. If all looks good on your end I can make a new release -- most likely after this gets fixed: https://github.com/backdrop-contrib/fivestar/issues/18

**Comment by laryn** [comment]
https://github.com/backdrop-contrib/fivestar/releases/tag/1.x-2.3.0
