### ISSUE TITLE
Error: Call to undefined function in fivestar_views_api()

### ISSUE THREAD

**Issue by pabloslab** [backdrop-contrib/fivestar#16]
In a fresh install of Backdrop 1.21.3, I got this error as soon as I added a fivestar field to any content type. It doesn't let you continue:

_Error: Call to undefined function drupal_get_path() in fivestar_views_api() (line 132 of mypath/modules/fivestar/fivestar.module)._

Steps to reproduce the error:

1. Set `backdrop_drupal_compatibility` to FALSE in settings.php
2. Add a fivestar field to a content type and save

**Comment by pabloslab** [comment]
Although enabling `backdrop_drupal_compatibility` gets rid of the error, I've sent PR #17 for testing.
Replacing the function to backdrop_get_path() has fixed it for me (regardless of backdrop-drupal compatibility mode).

**Comment by laryn** [comment]
Sorry for the delay, @pabloslab and thanks for reporting and fixing!
