### ISSUE TITLE
Error explode Argument on new sites

### ISSUE THREAD

**Issue by Acertijo** [backdrop-contrib/fivestar#22]
Error
explode(): Argument #2 ($string) must be of type string, array given 

I get this error on a new site, just after adding a Fivestar field
Tested in Backdrop 1.29.1 and 1.29.2

**Comment by laryn** [comment]
Verified on a demo sandbox. Here's a more verbose error:

> TypeError: explode(): Argument #2 ($string) must be of type string, array given in explode() (line 805 of /var/lib/tugboat/backdrop/modules/fivestar/fivestar.module).

**Comment by laryn** [comment]
@Acertijo Can you test the latest dev code rather than the latest release? If it looks good I will make a new release.

**Comment by marcel-7** [comment]
The above mentioned bug and the error message still exist, but only under PHP 8 + 8.1. Back to PHP 7.4 Fivestar can be configured and used without errors.

**Comment by laryn** [comment]
@marcel-7 Thanks for letting me know. However, I just tested on a fresh sandbox and did not have any issues on PHP 8.1.

Were you testing with release `1.x-2.3.0`?

**Comment by marcel-7** [comment]
yes, exactly - locally with ddev!

**Comment by marcel-7** [comment]
Perhaps the application description will give you an idea of what is causing the error? I do not use fivestar for voting, but several fivestar fields in a content type for classification according to various criteria. The installation went flawlessly, the said error appears as soon as you try to save the field. It is saved despite the message, but cannot be configured. Each time the configuration button is clicked, the following message appears again: `TypeError: explode(): Argument #2 ($string) must be of type string, array given in explode() (line 839 of /var/www/html/web/modules/fivestar/fivestar.module).` - identical to the previous version.

**Comment by marcel-7** [comment]
sorry, I have checked the logs again: The same error message in the previous version referred to line 805

**Comment by laryn** [comment]
@marcel-7 Can you paste the contents (or attach as a `.txt` file) the `fivestar.settings` json file from your config folder?

**Comment by marcel-7** [comment]
I will give it a try. I've known and tested Backdrop for about a week because I have an old D7 site... ;-)

**Comment by laryn** [comment]
Ha, no problem. And welcome! Alternately, paste this in the bottom of your `fivestar.install` file and run site updates.

```php
/**
 * Ensure tags variable is a string, not an array.
 * See: https://github.com/backdrop-contrib/fivestar/issues/22
 */
function fivestar_update_1202() {
  $config = config('fivestar.settings');
  $tags = $config->get('fivestar_tags');
  if (is_array($tags)) {
    $tags = implode(',', $tags);
    $config->set('fivestar_tags', $tags);
    $config->save();
  }
}
```

**Comment by marcel-7** [comment]
I did it: The error is gone!

**Comment by laryn** [comment]
@marcel-7 You've been using Backdrop for a week and you already have your first contrib credit 👍 👍 

![CleanShot 2024-12-05 at 15 49 08@2x](https://github.com/user-attachments/assets/49aeeaf7-6b2a-4447-9994-723e1638eafc)

**Comment by marcel-7** [comment]
Inzwischen hab ich auch entdeckt, dass jedes Modul einen config Ordner hat, wie praktisch... - meine fivestar.settings.json ist erschreckend umfangreich:

```
{
  "_config_name": "fivestar.settings",
  "fivestar_tags": "vote"
}
```

Das ist alles, aber jetzt vermutlich korrekt...

**Comment by marcel-7** [comment]
In the meantime I have also discovered that each module has a config folder, how practical... - my fivestar.settings.json is frighteningly extensive:

{
  “_config_name": ‘fivestar.settings’,
  “fivestar_tags": ”vote”
}

That's all, but probably correct now...

**Comment by laryn** [comment]
Some modules obviously have more settings in their config files. 😄
