### ISSUE TITLE
Widget not defaulting to "exposed"

### ISSUE THREAD

**Issue by whiteph** [backdrop-contrib/fivestar#5]
The widgets are "exposed", "stars", and "fivestar_select". In fivestar_field_info function, default_widget is set to "exposed". However, on the admin form, "fivestar_select" is the actual default shown to the user.

May be a recurrence of an old core bug #688 "Field default widgets are not actually set as defaults".

**Comment by laryn** [comment]
I think this issue may be outdated. Closing. (Reopen if you think I'm wrong).
